name: Deploy to GitHub pages

on:
  push:
    # this might change depending on whether you are publishing a site for a normal repo or a user/organization repo
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Generate static vuepress files
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: yarn install
    - run: yarn build

    - name: Force push to destination branch
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Destination branch to push changes
        branch: gh-pages
        # Use force push to fully overwrite the destination branch
        force: true
        # We have to push from the folder where files were generated.
        # Same were the new repo was initialized in the previous step
        directory: ./src/.vuepress/dist
